server:
  port: 9999

spring:
  application:
    name: webflux-gateway

  r2dbc:
    url: r2dbc:postgresql://localhost:16666/postgres
    username: pro
    password: pro

  sql:
    init:
      mode: always          # runs schema.sql / data.sql on startup
      schema-locations: classpath:script/data.sql