CREATE SEQUENCE IF NOT EXISTS api_route_id_seq START WITH 1;

CREATE TABLE IF NOT EXISTS api_routes(
    id BIGINT PRIMARY KEY DEFAULT nextval ('api_route_id_seq'),
    uri VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    method VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    group_code VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,

    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);