--liquibase formatted sql

--changeset admin:001-create-services-table
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255),
    description VARCHAR(255)
);

--changeset admin:002-create-api-routes-table
CREATE TABLE IF NOT EXISTS api_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri VARCHAR(255),
    path VARCHAR(255),
    method VARCHAR(50),
    description VARCHAR(255),
    group_code VARCHAR(255),
    status VARCHAR(50),
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,
    version BIGINT DEFAULT 0
);
